version: "3.8"

services:
  dev-quest-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-irl-hiscore-service-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dev_stripe
      DB_USER: dev_stripe_user
      DB_PASSWORD: turnip
    ports:
      - "8080:8080"
    networks:
      - dev-irl-network

networks:
  dev-irl-network:
    external: true
